// Generated by IB v0.6.0 gem. Do not edit it manually
// Run `rake ib:open` to refresh

#import <Quartz/Quartz.h>

@interface AppDelegate: NSObject <NSApplicationDelegate>

@property IBOutlet id window;
@property IBOutlet id mainTab;
@property IBOutlet id progressBar;
@property IBOutlet id appInfoObjCtl;
@property IBOutlet id modeSwitch;
@property IBOutlet id inputText;
@property IBOutlet id concSortSelect;
@property IBOutlet id concTableFrame;
@property IBOutlet id concTable;
@property IBOutlet id concContextView;
@property IBOutlet id plotBtn;
@property IBOutlet id fileController;
@property IBOutlet id fileController;
@property IBOutlet id concController;
@property IBOutlet id concExportEncodingView;
@property IBOutlet id encodingView;
@property IBOutlet id concOpenOptionView;
@property IBOutlet id fileSplitView;

-(IBAction) awakeFromNib;
-(IBAction) applicationDidFinishLaunching:(id) notification;
-(IBAction) localizeString:(id) string;
-(IBAction) windowDidBecomeKey:(id) notification;
-(IBAction) changeMode:(id) sender;
-(IBAction) refreshWindow;
-(IBAction) toolChange:(id) sender;
-(IBAction) concTableSizeAdjust;
-(IBAction) showPrefWindow:(id) sender;
-(IBAction) showConcFontPanel:(id) sender;
-(IBAction) showWCHandlingWindow:(id) sender;
-(IBAction) showReplaceCharsWindow:(id) sender;
-(IBAction) showLKWSPVWindow:(id) sender;
-(IBAction) showConcResultWindow:(id) sender;
-(IBAction) openSelectedFileInFinder:(id) item;
-(IBAction) openSelectedFileWithApp:(id) item;
-(IBAction) fileNotFoundWarning:(id) filename;
-(IBAction) saveResults:(id) sender;
-(IBAction) openSavedResults:(id) sender;
-(IBAction) exportResult:(id) sender;
-(IBAction) changeExportFileType:(id) sender;
-(IBAction) concExportProcess:(id) exportFilename;
-(IBAction) wcExportProcess:(id) exportFilename;
-(IBAction) revertToDefaultWindowSize:(id) sender;
-(IBAction) applicationShouldTerminateAfterLastWindowClosed:(id) application;
-(IBAction) applicationShouldTerminate:(id) notification;
-(IBAction) windowShouldClose:(id) notification;

@end

@interface CCStats: NSObject
-(IBAction) fact:(id) n;

@end

@interface ConcFontManagerController: NSWindowController

@property IBOutlet id allFontAryCtl;
@property IBOutlet id fontAryCtl;
@property IBOutlet id fontTable;
@property IBOutlet id fontChoice;

-(IBAction) windowNibName;
-(IBAction) awakeFromNib;
-(IBAction) addFont:(id) sender;
-(IBAction) removeFont:(id) sender;

@end

@interface Concord: NSObject

@property IBOutlet id currentFileListAry;
@property IBOutlet id corpusListAry;
@property IBOutlet id dbListAry;
@property IBOutlet id indexedDBListAry;
@property IBOutlet id concContextView;
@property IBOutlet id progressBar;
@property IBOutlet id concSearchBtn;
@property IBOutlet id concTable;
@property IBOutlet id searchWordHistoryAryCtl;
@property IBOutlet id contextWordHistryAryCtl;
@property IBOutlet id contextExcludeWordHistryAryCtl;
@property IBOutlet id appInfoObjCtl;
@property IBOutlet id fileController;

-(IBAction) awakeFromNib;
-(IBAction) applicationDidFinishLaunching:(id) notification;
-(IBAction) searchConcFromContext:(id) sender;
-(IBAction) searchConc:(id) sender;
-(IBAction) resortConcResult:(id) sender;
-(IBAction) concSort:(id) concResults;
-(IBAction) contextSpanCheck:(id) source;
-(IBAction) copyConcLines:(id) sender;
-(IBAction) deleteConcLine:(id) sender;
-(IBAction) addBackConcLines:(id) deletedItems;
-(IBAction) openSelectedFile:(id) sender;
-(IBAction) numberOfRowsInTableView:(id) tableView;
-(IBAction) tableViewSelectionDidChange:(id) notification;
-(IBAction) updatePreview:(id) sender;

@end

@interface ConcResultController: NSWindowController

@property IBOutlet id concTable;
@property IBOutlet id concContextView;
@property IBOutlet id contextCheck;
@property IBOutlet id concExportEncodingView;
@property IBOutlet id encodingChoice;
@property IBOutlet id appInfoObjCtl;
@property IBOutlet id concSortOrderChoices;

-(IBAction) windowNibName;
-(IBAction) concSort:(id) concResults;
-(IBAction) copyConcLines:(id) sender;
-(IBAction) exportResult:(id) sender;
-(IBAction) changeExportFileType:(id) sender;
-(IBAction) saveResults:(id) sender;
-(IBAction) deleteConcLine:(id) sender;
-(IBAction) addBackConcLines:(id) deletedItems;
-(IBAction) numberOfRowsInTableView:(id) tableView;
-(IBAction) tableViewSelectionDidChange:(id) notification;
-(IBAction) updatePreview:(id) sender;
-(IBAction) windowShouldClose:(id) window;

@end

@interface DBEditorWindowController: NSWindowController
-(IBAction) windowNibName;
-(IBAction) updateEntry:(id) sender;
-(IBAction) textDidChange:(id) notification;
-(IBAction) displayText:(id) item;
-(IBAction) windowShouldClose:(id) window;

@end

@interface EditorWindowController: NSWindowController
-(IBAction) windowNibName;
-(IBAction) awakeFromNib;
-(IBAction) setEditorText:(id) item;
-(IBAction) saveEditorDoc:(id) sender;
-(IBAction) windowShouldClose:(id) window;
-(IBAction) textDidChange:(id) notification;

@end

@interface FileController: NSObject

@property IBOutlet id mainWindow;
@property IBOutlet id currentFileListAry;
@property IBOutlet id currentFileListTable;
@property IBOutlet id filesToAddAry;
@property IBOutlet id corpusListAry;
@property IBOutlet id dbListAry;
@property IBOutlet id indexedDBListAry;
@property IBOutlet id contentListAry;
@property IBOutlet id encodingView;
@property IBOutlet id plotBtn;
@property IBOutlet id fileContentProgressCircle;
@property IBOutlet id selectedCorpusAryCtl;
@property IBOutlet id selectedDatabaseAryCtl;
@property IBOutlet id fileTable;
@property IBOutlet id filesToAddTable;
@property IBOutlet id corporaListTable;
@property IBOutlet id databaseListTable;
@property IBOutlet id indexedDatabaseListTable;
@property IBOutlet id cdContentsTable;
@property IBOutlet id filePreviewText;
@property IBOutlet id advFilePreviewText;
@property IBOutlet id createNewCDBtn;
@property IBOutlet id nameNewCDPanel;
@property IBOutlet id appInfoObjCtl;

-(IBAction) awakeFromNib;
-(IBAction) addFiles:(id) sender;
-(IBAction) removeFiles:(id) sender;
-(IBAction) clearTable:(id) sender;
-(IBAction) addNewCDEntry:(id) sender;
-(IBAction) createCDEntry:(id) sender;
-(IBAction) createCorpusEntryProcess:(id) newCDName;
-(IBAction) addFilesToCD:(id) sender;
-(IBAction) deleteFilesFromCD:(id) sender;
-(IBAction) mergeCDProcess:(id) newCDName;
-(IBAction) createNewDB:(id) sender;
-(IBAction) startNewDBCreationProcess:(id) sender;
-(IBAction) createNewDatabaseFile:(id) dbPath;
-(IBAction) startNewIndexedDBCreationProcess:(id) sender;
-(IBAction) createNewIndexedDatabaseFile:(id) filename;
-(IBAction) removeCDFromList:(id) sender;
-(IBAction) removeDBFromList:(id) sender;
-(IBAction) openSelectedFile:(id) sender;
-(IBAction) corpusSelectionChanged:(id) sender;
-(IBAction) addExistingDB:(id) sender;
-(IBAction) addExistingDBProcess:(id) filesAry;
-(IBAction) addExistingIndexedDBProcess:(id) filesAry;
-(IBAction) refreshPreview:(id) sender;
-(IBAction) refreshFileListTable:(id) sender;
-(IBAction) tableViewSelectionDidChange:(id) notification;
-(IBAction) importCorporaList:(id) sender;
-(IBAction) tagPreparation;
-(IBAction) numberOfRowsInTableView:(id) tableView;
-(IBAction) checkAllItems:(id) sender;
-(IBAction) selectIndexDB:(id) sender;

@end

@interface FileInfo: NSObject

@property IBOutlet id mainWindow;
@property IBOutlet id mainTab;
@property IBOutlet id appInfoObjCtl;
@property IBOutlet id fileController;
@property IBOutlet id concConctroller;
@property IBOutlet id wcController;
@property IBOutlet id collocController;
@property IBOutlet id clustController;
@property IBOutlet id fileInfoTable;
@property IBOutlet id fileInfoAryCtl;
@property IBOutlet id importWLAryCtl;
@property IBOutlet id importWLPanel;
@property IBOutlet id importWLTable;
@property IBOutlet id importWLTextPanel;
@property IBOutlet id importWLText;
@property IBOutlet id fiWLImportChoiceView;
@property IBOutlet id importKGPanel;
@property IBOutlet id importKGTable;
@property IBOutlet id importKGTextPanel;
@property IBOutlet id importWLText;
@property IBOutlet id importKGAryCtl;
@property IBOutlet id importKGText;
@property IBOutlet id startProcessBtn;
@property IBOutlet id currentFIType;
@property IBOutlet id itemOrder;
@property IBOutlet id groupingPanel;
@property IBOutlet id groupLabellingPanel;
@property IBOutlet id groupingAryCtl;
@property IBOutlet id groupLabelAryCtl;
@property IBOutlet id groupingTable;
@property IBOutlet id groupLabelTable;

-(IBAction) awakeFromNib;
-(IBAction) prepareFileInfo:(id) sender;
-(IBAction) selectWordList:(id) type;
-(IBAction) importWordList:(id) sender;
-(IBAction) importWLText:(id) sender;
-(IBAction) selectKeyGroupList:(id) sender;
-(IBAction) importKGList:(id) sender;
-(IBAction) closeKGListPanel:(id) sender;
-(IBAction) importKGText:(id) sender;
-(IBAction) pasteKGText:(id) sender;
-(IBAction) processLemmatize:(id) sender;
-(IBAction) startFileInfoProcess:(id) sender;
-(IBAction) fileInfoProcess:(id) fiMode;
-(IBAction) tableProcess:(id) fiMode;
-(IBAction) fileInfoTableProcess;
-(IBAction) wordListTableProcess:(id) type;
-(IBAction) tfidfTableProcess;
-(IBAction) showGroupingPanel:(id) sender;
-(IBAction) closeGroupingPanel:(id) sender;
-(IBAction) showGroupLabellingPanel:(id) sender;
-(IBAction) closeGroupLabellingPanel:(id) sender;
-(IBAction) deleteFileInfoLines:(id) sender;
-(IBAction) addBackFileInfoLines:(id) deletedItems;
-(IBAction) copySelectedLines:(id) sender;
-(IBAction) numberOfRowsInTableView:(id) tableView;

@end

@interface LemmaKYGSPVarListController: NSWindowController

@property IBOutlet id lkpTabView;
@property IBOutlet id lkpGroupTabView;
@property IBOutlet id appInfoObjCtl;
@property IBOutlet id encodingView;
@property IBOutlet id splitView;
@property IBOutlet id importChoiceView;
@property IBOutlet id progressCircle;
@property IBOutlet id removeGroupBtn;
@property IBOutlet id removeEntryBtn;
@property IBOutlet id exportEntryListBtn;
@property IBOutlet id importEntryListBtn;
@property IBOutlet id rebuldBtn;
@property IBOutlet id delDupBtn;
@property IBOutlet id keywordText;
@property IBOutlet id wordsText;
@property IBOutlet id lemmaAryCtl;
@property IBOutlet id keywordAryCtl;
@property IBOutlet id spellVarAryCtl;
@property IBOutlet id lemmaGroupAryCtl;
@property IBOutlet id keywordGroupAryCtl;
@property IBOutlet id spellVarGroupAryCtl;
@property IBOutlet id lemmaTable;
@property IBOutlet id kwgTable;
@property IBOutlet id spellVarTable;
@property IBOutlet id lemmaGroupTable;
@property IBOutlet id keywordGroupTable;
@property IBOutlet id spellVarGroupTable;
@property IBOutlet id keywordHashes;
@property IBOutlet id initialGroup;

-(IBAction) windowNibName;
-(IBAction) awakeFromNib;
-(IBAction) changeTabView:(id) sender;
-(IBAction) addGroup:(id) sender;
-(IBAction) removeGroup:(id) sender;
-(IBAction) addNewEntry:(id) sender;
-(IBAction) removeEntry:(id) sender;
-(IBAction) importList:(id) sender;
-(IBAction) exportList:(id) sender;
-(IBAction) rebuildData:(id) sender;
-(IBAction) updateWordList:(id) sender;
-(IBAction) tableViewSelectionDidChange:(id) notification;
-(IBAction) windowDidBecomeKey:(id) notification;
-(IBAction) windowDidResignKey:(id) notification;
-(IBAction) windowDidResize:(id) notification;

@end

@interface ListItemProcesses: NSObject
-(IBAction) init;
-(IBAction) stopWordPrepare;
-(IBAction) skipCharPrepare;
-(IBAction) includeWordPrepare;
-(IBAction) multiWordPrepare;
-(IBAction) lemmaPrepare;
-(IBAction) kwgPrepare;
-(IBAction) spvPrepare;
-(IBAction) charReplacePrepare;
-(IBAction) includeAsPartWordPrepare;
-(IBAction) eosWordPrepare;

@end

@interface MyNumFormatter: NSNumberFormatter
-(IBAction) textAttributesForNegativeValues;

@end

@interface MyTableView: NSTableView
-(IBAction) textDidBeginEditing:(id) notification;
-(IBAction) textDidEndEditing:(id) notification;

@end

@interface MyNonEdTableView: NSTableView
-(IBAction) menuForEvent:(id) event;

@end

@interface MyNonEdTableHeaderView: NSTableHeaderView
-(IBAction) menuForEvent:(id) event;

@end

@interface Preferences: NSWindowController

@property IBOutlet id prefTab;
@property IBOutlet id selectFileTypesPanel;
@property IBOutlet id selectAppForFilePanel;
@property IBOutlet id sortOrderPanel;
@property IBOutlet id sortOrder1;
@property IBOutlet id sortOrder2;
@property IBOutlet id sortOrder3;
@property IBOutlet id sortOrder4;
@property IBOutlet id sortOrderAryCtl;
@property IBOutlet id sortOrderTable;
@property IBOutlet id coloringTable;
@property IBOutlet id sectionTagsAryCtl;
@property IBOutlet id ignoreStringsAryCtl;

-(IBAction) windowNibName;
-(IBAction) awakeFromNib;
-(IBAction) changeCorpusMode:(id) sender;
-(IBAction) prefTabChange:(id) sender;
-(IBAction) openSelectAcceptFileTypes:(id) sender;
-(IBAction) closeSelectAcceptFileTypes:(id) sender;
-(IBAction) openSelectAppForFile:(id) sender;
-(IBAction) closeSelectAppForFile:(id) sender;
-(IBAction) openSortOrderPresetEditor:(id) sender;
-(IBAction) addSortOrder:(id) sender;
-(IBAction) removeSortOrder:(id) sender;
-(IBAction) restoreDefaultSortOrder:(id) sender;
-(IBAction) selectAppForFile:(id) sender;
-(IBAction) selectDefaultFolder:(id) sender;
-(IBAction) resetContextColors:(id) sender;
-(IBAction) changeContextWordStyle:(id) sender;
-(IBAction) numberOfRowsInTableView:(id) tableView;
-(IBAction) windowDidBecomeKey:(id) notification;
-(IBAction) windowWillClose:(id) notification;
-(IBAction) windowDidResignKey:(id) notification;

@end

@interface ReplaceCharController: NSWindowController

@property IBOutlet id appInfoObjCtl;
@property IBOutlet id replaceCharAryCtl;
@property IBOutlet id encodingView;
@property IBOutlet id changeFlag;

-(IBAction) windowNibName;
-(IBAction) awakeFromNib;
-(IBAction) addNewEntry:(id) sender;
-(IBAction) clearTable:(id) sender;
-(IBAction) removeEntries:(id) sender;
-(IBAction) importEntries:(id) sender;
-(IBAction) exportEntries:(id) sender;
-(IBAction) windowDidBecomeKey:(id) notification;
-(IBAction) windowDidResignKey:(id) notification;

@end

@interface MyString: String
-(IBAction) init:(id) inText;
-(IBAction) toSql;
-(IBAction) initialize:(id) sou;

@end

@interface WildWordProcess: NSObject
-(IBAction) initialize:(id) source;

@end

@interface ArrayExistTransformer: NSValueTransformer
-(IBAction) transformedValueClass;
-(IBAction) allowsReverseTransformation;
-(IBAction) transformedValue:(id) value;

@end

@interface ValueZeroSelectedTransformer: NSValueTransformer
-(IBAction) transformedValueClass;
-(IBAction) allowsReverseTransformation;
-(IBAction) transformedValue:(id) value;

@end

@interface ValueOneSelectedTransformer: NSValueTransformer
-(IBAction) transformedValueClass;
-(IBAction) allowsReverseTransformation;
-(IBAction) transformedValue:(id) value;

@end

@interface ArrayLengthTransformer: NSValueTransformer
-(IBAction) transformedValueClass;
-(IBAction) allowsReverseTransformation;
-(IBAction) transformedValue:(id) value;

@end

@interface ArrayLengthMoreThanOneTransformer: NSValueTransformer
-(IBAction) transformedValueClass;
-(IBAction) allowsReverseTransformation;
-(IBAction) transformedValue:(id) value;

@end

@interface ValueTwoNotSelectedTransformer: NSValueTransformer
-(IBAction) transformedValueClass;
-(IBAction) allowsReverseTransformation;
-(IBAction) transformedValue:(id) value;

@end

@interface ValueTwoSelectedTransformer: NSValueTransformer
-(IBAction) transformedValueClass;
-(IBAction) allowsReverseTransformation;
-(IBAction) transformedValue:(id) value;

@end

@interface GetGroupValueTransformer: NSValueTransformer
-(IBAction) transformedValueClass;
-(IBAction) allowsReverseTransformation;
-(IBAction) transformedValue:(id) value;

@end

@interface GetLocalizedFontNameTransformer: NSValueTransformer
-(IBAction) transformedValueClass;
-(IBAction) allowsReverseTransformation;
-(IBAction) transformedValue:(id) value;
-(IBAction) a;

@end

@interface TwoObjectsSelectedTransformer: NSValueTransformer
-(IBAction) transformedValueClass;
-(IBAction) allowsReverseTransformation;
-(IBAction) transformedValue:(id) value;

@end

@interface ArrayLengthZeroTransformer: NSValueTransformer
-(IBAction) transformedValueClass;
-(IBAction) allowsReverseTransformation;
-(IBAction) transformedValue:(id) value;

@end

@interface TableRowHeightAdjustTransformer: NSValueTransformer
-(IBAction) transformedValueClass;
-(IBAction) allowsReverseTransformation;
-(IBAction) transformedValue:(id) value;

@end

@interface ValueOneNotSelectedTransformer: NSValueTransformer
-(IBAction) transformedValueClass;
-(IBAction) allowsReverseTransformation;
-(IBAction) transformedValue:(id) value;

@end

@interface ValueThreeNotSelectedTransformer: NSValueTransformer
-(IBAction) transformedValueClass;
-(IBAction) allowsReverseTransformation;
-(IBAction) transformedValue:(id) value;

@end

@interface ValueThreeSelectedTransformer: NSValueTransformer
-(IBAction) transformedValueClass;
-(IBAction) allowsReverseTransformation;
-(IBAction) transformedValue:(id) value;

@end

@interface ValueZeroNotSelectedTransformer: NSValueTransformer
-(IBAction) transformedValueClass;
-(IBAction) allowsReverseTransformation;
-(IBAction) transformedValue:(id) value;

@end

@interface ValueNineNotSelectedTransformer: NSValueTransformer
-(IBAction) transformedValueClass;
-(IBAction) allowsReverseTransformation;
-(IBAction) transformedValue:(id) value;

@end

@interface ValueOneTwoNotSelectedTransformer: NSValueTransformer
-(IBAction) transformedValueClass;
-(IBAction) allowsReverseTransformation;
-(IBAction) transformedValue:(id) value;

@end

@interface ValueZeroToTrueTransformer: NSValueTransformer
-(IBAction) transformedValueClass;
-(IBAction) allowsReverseTransformation;
-(IBAction) transformedValue:(id) value;

@end

@interface ValueOneToTrueTransformer: NSValueTransformer
-(IBAction) transformedValueClass;
-(IBAction) allowsReverseTransformation;
-(IBAction) transformedValue:(id) value;

@end

@interface WCGapContentsController: NSWindowController

@property IBOutlet id gapWordTable;
@property IBOutlet id gapWordAry;
@property IBOutlet id appInfoObjCtl;

-(IBAction) windowNibName;
-(IBAction) awakeFromNib;
-(IBAction) windowDidLoad;
-(IBAction) copyItems:(id) sender;

@end

@interface WCLemmaContentsController: NSWindowController

@property IBOutlet id lemmaTable;
@property IBOutlet id lemmaAry;
@property IBOutlet id appInfoObjCtl;

-(IBAction) windowNibName;
-(IBAction) awakeFromNib;
-(IBAction) windowDidLoad;
-(IBAction) copyItems:(id) sender;

@end

@interface WCResultWindowController: NSWindowController
-(IBAction) windowNibName;
-(IBAction) awakeFromNib;
-(IBAction) saveResult:(id) sender;
-(IBAction) exportResult:(id) sender;

@end

@interface WordCharHandlingController: NSWindowController

@property IBOutlet id wchTabView;
@property IBOutlet id removeWordBtn;
@property IBOutlet id exportWordListBtn;
@property IBOutlet id appInfoObjCtl;
@property IBOutlet id encodingView;
@property IBOutlet id importListFromGroupPanel;
@property IBOutlet id splitView;
@property IBOutlet id groupTable;
@property IBOutlet id stopWordTable;
@property IBOutlet id skipCharTable;
@property IBOutlet id includeWordTable;
@property IBOutlet id multiWordTable;
@property IBOutlet id nonEOSWordTable;
@property IBOutlet id groupAryCtl;
@property IBOutlet id stopWordAryCtl;
@property IBOutlet id skipCharAryCtl;
@property IBOutlet id includeWordAryCtl;
@property IBOutlet id multiWordAryCtl;
@property IBOutlet id nonEOSWordAryCtl;
@property IBOutlet id initialGroup;

-(IBAction) windowNibName;
-(IBAction) awakeFromNib;
-(IBAction) addGroup:(id) sender;
-(IBAction) removeGroup:(id) sender;
-(IBAction) addNewWord:(id) sender;
-(IBAction) removeWord:(id) sender;
-(IBAction) importWordList:(id) sender;
-(IBAction) importWordListFromGroup:(id) sender;
-(IBAction) exportWordList:(id) sender;
-(IBAction) changeTabView:(id) sender;
-(IBAction) updateWordList:(id) sender;
-(IBAction) tableViewSelectionDidChange:(id) notification;
-(IBAction) numberOfRowsInTableView:(id) tableView;
-(IBAction) windowDidResize:(id) notification;
-(IBAction) windowDidBecomeKey:(id) notification;
-(IBAction) windowDidResignKey:(id) notification;

@end

@interface WordCount: NSObject

@property IBOutlet id mainWindow;
@property IBOutlet id mainTab;
@property IBOutlet id wcLeftAryCtl;
@property IBOutlet id wcRightAryCtl;
@property IBOutlet id appInfoObjCtl;
@property IBOutlet id wcLeftTable;
@property IBOutlet id wcRightTable;
@property IBOutlet id fileController;
@property IBOutlet id concController;
@property IBOutlet id currentFileListAry;
@property IBOutlet id corpusListAry;
@property IBOutlet id dbListAry;
@property IBOutlet id selectedCorpusAryCtl;
@property IBOutlet id selectedDatabaseAryCtl;

-(IBAction) awakeFromNib;
-(IBAction) countWords:(id) sender;
-(IBAction) createWordList:(id) tableID;
-(IBAction) createNgramList:(id) tableID;
-(IBAction) createGapNgramList:(id) tableID;
-(IBAction) resortList:(id) sender;
-(IBAction) searchInConcord:(id) sender;
-(IBAction) copySelectedLines:(id) sender;
-(IBAction) calcKeyword:(id) sender;
-(IBAction) showGapWordList:(id) sender;
-(IBAction) showLemmaWordList:(id) sender;

@end

