// Generated by IB v0.6.0 gem. Do not edit it manually
// Run `rake ib:open` to refresh

#import "Stubs.h"

@implementation AppDelegate
@end

@implementation CCStats
@end

@implementation ConcFontManagerController
@end

@implementation Concord
@end

@implementation ConcResultController
@end

@implementation DBEditorWindowController
@end

@implementation EditorWindowController
@end

@implementation FileController
@end

@implementation FileInfo
@end

@implementation LemmaKYGSPVarListController
@end

@implementation ListItemProcesses
@end

@implementation MyNumFormatter
@end

@implementation MyTableView
@end

@implementation MyNonEdTableView
@end

@implementation MyNonEdTableHeaderView
@end

@implementation Preferences
@end

@implementation ReplaceCharController
@end

@implementation MyString
@end

@implementation WildWordProcess
@end

@implementation ArrayExistTransformer
@end

@implementation ValueZeroSelectedTransformer
@end

@implementation ValueOneSelectedTransformer
@end

@implementation ArrayLengthTransformer
@end

@implementation ArrayLengthMoreThanOneTransformer
@end

@implementation ValueTwoNotSelectedTransformer
@end

@implementation ValueTwoSelectedTransformer
@end

@implementation GetGroupValueTransformer
@end

@implementation GetLocalizedFontNameTransformer
@end

@implementation TwoObjectsSelectedTransformer
@end

@implementation ArrayLengthZeroTransformer
@end

@implementation TableRowHeightAdjustTransformer
@end

@implementation ValueOneNotSelectedTransformer
@end

@implementation ValueThreeNotSelectedTransformer
@end

@implementation ValueThreeSelectedTransformer
@end

@implementation ValueZeroNotSelectedTransformer
@end

@implementation ValueNineNotSelectedTransformer
@end

@implementation ValueOneTwoNotSelectedTransformer
@end

@implementation ValueZeroToTrueTransformer
@end

@implementation ValueOneToTrueTransformer
@end

@implementation WCGapContentsController
@end

@implementation WCLemmaContentsController
@end

@implementation WCResultWindowController
@end

@implementation WordCharHandlingController
@end

@implementation WordCount
@end

